export const ROLES = {
  EMPLOYEE: 'Employee',
  MANAGER: 'Manager',
  ADMIN: 'Administrator'
};

export const LEAVE_TYPES = {
  PL: 'PL',
  SL: 'SL',
  MCL: 'MCL',
  COMP_OFF: 'Comp-Off'
};

export const LEAVE_REQUEST_STATUS = {
  PENDING: 'PENDING',
  MANAGER_APPROVED: 'MANAGER_APPROVED',
  ADMIN_APPROVED: 'ADMIN_APPROVED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

export const APPROVAL_STATUS = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

export const APPROVER_ROLE = {
  MANAGER: 'MANAGER',
  ADMIN: 'ADMIN'
};

export const HOLIDAY_TYPE = {
  PUBLIC: 'PUBLIC',
  COMPANY: 'COMPANY',
  REGIONAL: 'REGIONAL'
};

export const BLOOD_RELATIONS = [
  'FATHER',
  'MOTHER',
  'GRANDFATHER',
  'GRANDMOTHER',
  'FATHER_IN_LAW',
  'MOTHER_IN_LAW'
];

export const BALANCE_CHANGE_REASON = {
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',
  CARRYFORWARD: 'CARRYFORWARD',
  MANUAL_ADJUSTMENT: 'MANUAL_ADJUSTMENT',
  YEARLY_RESET: 'YEARLY_RESET'
};

export const NOTIFICATION_TYPE = {
  LEAVE_APPLIED: 'LEAVE_APPLIED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',
  BALANCE_LOW: 'BALANCE_LOW'
};

export const AUDIT_ACTION = {
  LEAVE_APPLIED: 'LEAVE_APPLIED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',
  BALANCE_UPDATED: 'BALANCE_UPDATED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  HOLIDAY_CREATED: 'HOLIDAY_CREATED',
  HOLIDAY_UPDATED: 'HOLIDAY_UPDATED'
};

export const EVENTS = {
  LEAVE_APPLIED: 'leave:applied',
  LEAVE_CANCELLED: 'leave:cancelled',
  LEAVE_APPROVED: 'leave:approved',
  LEAVE_REJECTED: 'leave:rejected',
  BALANCE_UPDATED: 'balance:updated',
  BALANCE_LOW: 'balance:low'
};
